### ISSUE TITLE
今天无法听歌了

### ISSUE THREAD

**Issue by FrederickChen** [yizhiheng/unblock-netease-music#1]
前天按你的方法自己搭建了一台代理，当时工作正常，今天发现PC网页上听不了歌，但是播放按钮不是灰色的。我用chrome的开发工具查看当前网页源码，发现音乐文件的src地址是http://m10.music.126.net/20170426204542/1290c9b6029e993a4e7cb7ed4cfd449a/ymusic/9ebf/0d46/0bd0/b325afa0ab1b9984b47275369080cdd4.mp3。
怀疑是网易服务器端自动检测到的服务器是代理了。
我的想法是，参照music.163.com的设置，在proxy.conf中为ｍ10.music.126.net再加一个虚拟server的block，
然后在hosts相应增加一行。是不是就解决这个问题了？
有空我去试试

**Comment by FrederickChen** [comment]
刚刚试了，还是不行。
注意到dokcer attach到运行nginx的容器中看到这样几行日志：
2017/04/26 13:24:03 [alert] 5#5: 1024 worker_connections are not enough
2017/04/26 13:24:03 [error] 5#5: *9234 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: m10.music.126.net, request: "GET /20170426214853/4b882066868a71680bd8684158b53983/ymusic/9ebf/0d46/0bd0/b325afa0ab1b9984b47275369080cdd4.mp3 HTTP/1.0", upstream: "http://127.0.0.1:80/20170426214853/4b882066868a71680bd8684158b53983/ymusic/9ebf/0d46/0bd0/b325afa0ab1b9984b47275369080cdd4.mp3", host: "m10.music.126.net", referrer: "http://music.163.com/"

没辙了，请问你遇到过同样的问题吗？

**Comment by yizhiheng** [comment]
抱歉, 这么久才看到回复...
请问你现在的问题解决了吗?

**Comment by FrederickChen** [comment]
解决了，我就是换了一个IP，后来一直工作正常。
忘了过来跟你说了。

**Comment by yizhiheng** [comment]
@G-F-CH 好的
