### ISSUE TITLE
服务器还开着吗

### ISSUE THREAD

**Issue by ain-soph** [yizhiheng/unblock-netease-music#5]
`207.148.27.51`虽然能ping通，但貌似所有服务都已经停了？我看最近一次commit的readme改动，是已经不维护服务器了吗？

**Comment by yizhiheng** [comment]
对, 我升级网易云客户端以后发现代理不好用了, 想着说可能也没什么人用了🙁, 所以就关掉了省点服务器的钱..

你可以试试这个repo https://github.com/fengjueming/unblock-NetEaseMusic里提供的?
